### ISSUE TITLE
AppDelegate.swift 中怎么初始化

### ISSUE THREAD

**Issue by sanrixue** [best-flutter/flutter_jpush#20]
AppDelegate.swift 中 怎么加入这段OC的代码 我在桥中已经搭了 但是调用的时候 无法按oc的方法来调用

**Comment by xiebaoxin** [comment]
参考 AppDelegate.swift 怎么集成key #12
https://github.com/best-flutter/flutter_jpush/issues/12 

就这样就可以么？
以下。h文件中增加的
[self startupJPush:launchOptions appKey:@"你的key" channel:@"你的渠道" isProduction:是否生产版本];

这一信息不用设置么
